name: test

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.2'
    - name: Test CLI
      run: |
        go version
        go run score.go -h
        go run score.go -l